INSERT INTO public."users.Country" (name, code, area_code) VALUES
('Afghanistan', 'AF', '93'),
('Albania', 'AL', '355'),
('Algeria', 'DZ', '213'),
('Andorra', 'AD', '376'),
('Angola', 'AO', '244'),
('Argentina', 'AR', '54'),
('Armenia', 'AM', '374'),
('Australia', 'AU', '61'),
('Austria', 'AT', '43'),
('Azerbaijan', 'AZ', '994'),
('Bahamas', 'BS', '1242'),
('Bahrain', 'BH', '973'),
('Bangladesh', 'BD', '880'),
('Barbados', 'BB', '1246'),
('Belarus', 'BY', '375'),
('Belgium', 'BE', '32'),
('Belize', 'BZ', '501'),
('Benin', 'BJ', '229'),
('Bolivia', 'BO', '591'),
('Brazil', 'BR', '55'),
('Bulgaria', 'BG', '359'),
('Cambodia', 'KH', '855'),
('Cameroon', 'CM', '237'),
('Canada', 'CA', '1'),
('Chile', 'CL', '56'),
('China', 'CN', '86'),
('Colombia', 'CO', '57'),
('Costa Rica', 'CR', '506'),
('Croatia', 'HR', '385'),
('Cuba', 'CU', '53'),
('Cyprus', 'CY', '357'),
('Czech Republic', 'CZ', '420'),
('Denmark', 'DK', '45'),
('Dominican Republic', 'DO', '1809'),
('Ecuador', 'EC', '593'),
('Egypt', 'EG', '20'),
('El Salvador', 'SV', '503'),
('Estonia', 'EE', '372'),
('Finland', 'FI', '358'),
('France', 'FR', '33'),
('Germany', 'DE', '49'),
('Greece', 'GR', '30'),
('Guatemala', 'GT', '502'),
('Haiti', 'HT', '509'),
('Honduras', 'HN', '504'),
('Hungary', 'HU', '36'),
('Iceland', 'IS', '354'),
('India', 'IN', '91'),
('Indonesia', 'ID', '62'),
('Iran', 'IR', '98'),
('Iraq', 'IQ', '964'),
('Ireland', 'IE', '353'),
('Israel', 'IL', '972'),
('Italy', 'IT', '39'),
('Jamaica', 'JM', '1876'),
('Japan', 'JP', '81'),
('Jordan', 'JO', '962'),
('Kazakhstan', 'KZ', '7'),
('Kenya', 'KE', '254'),
('Kuwait', 'KW', '965'),
('Latvia', 'LV', '371'),
('Lebanon', 'LB', '961'),
('Libya', 'LY', '218'),
('Lithuania', 'LT', '370'),
('Luxembourg', 'LU', '352'),
('Malaysia', 'MY', '60'),
('Mexico', 'MX', '52'),
('Monaco', 'MC', '377'),
('Mongolia', 'MN', '976'),
('Morocco', 'MA', '212'),
('Nepal', 'NP', '977'),
('Netherlands', 'NL', '31'),
('New Zealand', 'NZ', '64'),
('Nicaragua', 'NI', '505'),
('Nigeria', 'NG', '234'),
('Norway', 'NO', '47'),
('Pakistan', 'PK', '92'),
('Panama', 'PA', '507'),
('Paraguay', 'PY', '595'),
('Peru', 'PE', '51'),
('Philippines', 'PH', '63'),
('Poland', 'PL', '48'),
('Portugal', 'PT', '351'),
('Qatar', 'QA', '974'),
('Romania', 'RO', '40'),
('Russia', 'RU', '7'),
('Saudi Arabia', 'SA', '966'),
('Singapore', 'SG', '65'),
('Slovakia', 'SK', '421'),
('Slovenia', 'SI', '386'),
('South Africa', 'ZA', '27'),
('South Korea', 'KR', '82'),
('Spain', 'ES', '34'),
('Sweden', 'SE', '46'),
('Switzerland', 'CH', '41'),
('Syria', 'SY', '963'),
('Taiwan', 'TW', '886'),
('Thailand', 'TH', '66'),
('Turkey', 'TR', '90'),
('Ukraine', 'UA', '380'),
('United Arab Emirates', 'AE', '971'),
('United Kingdom', 'GB', '44'),
('United States', 'US', '1'),
('Uruguay', 'UY', '598'),
('Venezuela', 'VE', '58'),
('Vietnam', 'VN', '84'),
('Yemen', 'YE', '967');
